/**
 * Steam Market Sticker Search
 *
 * Finds CS2 weapon listings with specific stickers applied.
 * Uses the per-listing filter endpoint on Steam Market.
 *
 * Usage:
 *   bun search.ts                          # smart scan (FT first, expand hits)
 *   bun search.ts --full                   # check every wear variant
 *   bun search.ts --resume                 # resume from checkpoint
 *   bun search.ts --sticker "Crown (Foil)" # single sticker
 */

const STICKERS = ["Katowice 2014", "Howling Dawn", "Crown (Foil)"];
const WEARS = ["Factory New", "Minimal Wear", "Field-Tested", "Well-Worn", "Battle-Scarred"];
const PRIMARY_WEAR = "Field-Tested"; // Most common wear, checked first in smart mode

const DELAY_MS = 3500;
const RATE_LIMIT_WAIT_MS = 65_000;
const MAX_RETRIES = 4;
const RESULTS_FILE = "results.json";
const CHECKPOINT_FILE = "checkpoint.json";
const SKINS_CACHE_FILE = "skins_cache.json";

interface StickerResult {
  skin: string;
  sticker: string;
  totalListings: number;
  cheapest?: number;
  marketUrl: string;
  checkedAt: string;
}

interface Checkpoint {
  phase: "primary" | "expand";
  index: number;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

let consecutiveFailures = 0;

async function fetchJSON(url: string): Promise<any> {
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const res = await fetch(url, {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
          Accept: "application/json, text/javascript, */*",
          Referer: "https://steamcommunity.com/market/",
        },
      });

      if (res.status === 429) {
        console.log(`  [429 rate-limited] waiting 65s...`);
        consecutiveFailures++;
        await sleep(RATE_LIMIT_WAIT_MS);
        continue;
      }
      if (!res.ok) {
        console.log(`  [HTTP ${res.status}] attempt ${attempt}/${MAX_RETRIES}`);
        consecutiveFailures++;
        await sleep(DELAY_MS * 3);
        continue;
      }

      const data = await res.json();
      if (data.success === false) {
        if (attempt < MAX_RETRIES) {
          console.log(`  [throttled] waiting 65s (attempt ${attempt})...`);
          consecutiveFailures++;
          await sleep(RATE_LIMIT_WAIT_MS);
          continue;
        }
        // On last attempt, return it anyway — total_count:0 is still valid
      }
      consecutiveFailures = 0;
      return data;
    } catch (err: any) {
      console.log(`  [error] ${err.message} (attempt ${attempt}/${MAX_RETRIES})`);
      consecutiveFailures++;
      await sleep(DELAY_MS * 3);
    }
  }
  return null;
}

async function checkSkin(skin: string, sticker: string): Promise<StickerResult | null> {
  const url =
    `https://steamcommunity.com/market/listings/730/${encodeURIComponent(skin)}/render/` +
    `?filter=${encodeURIComponent(sticker)}&start=0&count=1&currency=1&language=english`;

  const data = await fetchJSON(url);
  if (!data) return null;
  const total = data.total_count ?? 0;
  if (total === 0) return null;

  let cheapest: number | undefined;
  if (data.listinginfo) {
    const prices = Object.values(data.listinginfo)
      .map((l: any) =>
        l.converted_price != null && l.converted_fee != null
          ? (l.converted_price + l.converted_fee) / 100
          : null
      )
      .filter((p): p is number => p !== null);
    if (prices.length) cheapest = Math.min(...prices);
  }

  return {
    skin,
    sticker,
    totalListings: total,
    cheapest,
    marketUrl: `https://steamcommunity.com/market/listings/730/${encodeURIComponent(skin)}?filter=${encodeURIComponent(sticker)}`,
    checkedAt: new Date().toISOString(),
  };
}

// Persistence helpers
const saveResults = (r: StickerResult[]) => Bun.write(RESULTS_FILE, JSON.stringify(r, null, 2));
const saveCheckpoint = (cp: Checkpoint) => Bun.write(CHECKPOINT_FILE, JSON.stringify(cp));

async function gitPush(message: string) {
  if (!args.includes("--push")) return;
  try {
    const proc = Bun.spawnSync(["bash", "-c",
      `cd "${import.meta.dir}" && git add results.json && git diff --cached --quiet || git commit -m "${message}" && git push`
    ]);
    if (proc.exitCode === 0) {
      console.log(`  [git] pushed: ${message}`);
    }
  } catch {}
}
const loadCheckpoint = async (): Promise<Checkpoint | null> => {
  try { return await Bun.file(CHECKPOINT_FILE).json(); } catch { return null; }
};
const loadResults = async (): Promise<StickerResult[]> => {
  try { return await Bun.file(RESULTS_FILE).json(); } catch { return []; }
};

// Load skins from cache (generated by setup step)
async function loadSkins(): Promise<string[]> {
  try {
    const data: string[] = await Bun.file(SKINS_CACHE_FILE).json();
    return data;
  } catch {
    console.error(`ERROR: ${SKINS_CACHE_FILE} not found. Run the setup first.`);
    process.exit(1);
  }
}

/** Extract base skin name: "AK-47 | Redline (Field-Tested)" -> "AK-47 | Redline" */
function baseName(hashName: string): string {
  return hashName.replace(/\s*\([^)]+\)\s*$/, "").replace(/^(StatTrak™|Souvenir)\s+/, "");
}

/** Get all variants of a base skin from the full list */
function getVariants(allSkins: string[], base: string): string[] {
  return allSkins.filter((s) => baseName(s) === base);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
const args = process.argv.slice(2);
const resumeMode = args.includes("--resume");
const fullMode = args.includes("--full");
const stickerIdx = args.indexOf("--sticker");
const stickersToSearch = stickerIdx >= 0 ? [args[stickerIdx + 1]] : STICKERS;

console.log("=== Steam Market Sticker Search ===");
console.log(`Stickers: ${stickersToSearch.join(", ")}`);
console.log(`Mode: ${fullMode ? "FULL (all wears)" : "SMART (FT first, expand hits)"}`);
console.log(`Rate limit delay: ${DELAY_MS}ms\n`);

const allSkins = await loadSkins();
console.log(`Loaded ${allSkins.length} skin variants from cache`);

// Build unique base skin names for smart mode
const baseNames = [...new Set(allSkins.map(baseName))].sort();
console.log(`Unique base skins: ${baseNames.length}`);

let results = resumeMode ? await loadResults() : [];
const cp = resumeMode ? await loadCheckpoint() : null;

const startTime = Date.now();
let checked = 0;

if (fullMode) {
  // Full mode: check every skin variant × sticker
  const jobs: { skin: string; sticker: string }[] = [];
  for (const skin of allSkins) {
    for (const sticker of stickersToSearch) {
      jobs.push({ skin, sticker });
    }
  }
  const startIdx = cp?.index ?? 0;
  const total = jobs.length;
  const estMin = Math.ceil(((total - startIdx) * DELAY_MS) / 60_000);
  console.log(`\nTotal queries: ${total} (starting from #${startIdx})`);
  console.log(`Est. time: ~${estMin} min (~${(estMin / 60).toFixed(1)} hrs)\n`);

  for (let i = startIdx; i < jobs.length; i++) {
    const { skin, sticker } = jobs[i];
    checked++;
    const pct = ((i / total) * 100).toFixed(1);
    const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);
    process.stdout.write(`[${pct}% ${elapsed}m] ${skin} | ${sticker}... `);

    const result = await checkSkin(skin, sticker);
    if (result) {
      console.log(`FOUND ${result.totalListings} @ $${result.cheapest?.toFixed(2) ?? "?"}`);
      results.push(result);
    } else {
      console.log("-");
    }

    if (checked % 10 === 0) {
      await saveCheckpoint({ phase: "primary", index: i + 1 });
      await saveResults(results);
      if (checked % 50 === 0) await gitPush(`update results: ${results.length} found (${((i / jobs.length) * 100).toFixed(0)}%)`);
    }

    // Adaptive delay: back off more if we're hitting rate limits
    const delay = consecutiveFailures > 2 ? DELAY_MS * 2 : DELAY_MS;
    await sleep(delay);
  }
} else {
  // Smart mode: check FT first, then expand hits to all variants
  // Phase 1: Check each base skin in Field-Tested only
  const primaryJobs: { base: string; ftSkin: string; sticker: string }[] = [];
  for (const base of baseNames) {
    const ftSkin = allSkins.find(
      (s) => baseName(s) === base && s.includes(`(${PRIMARY_WEAR})`) && !s.startsWith("StatTrak") && !s.startsWith("Souvenir")
    );
    if (!ftSkin) continue;
    for (const sticker of stickersToSearch) {
      primaryJobs.push({ base, ftSkin, sticker });
    }
  }

  let primaryStart = 0;
  let expandStart = 0;
  if (cp?.phase === "primary") primaryStart = cp.index;
  if (cp?.phase === "expand") {
    primaryStart = primaryJobs.length; // skip primary
    expandStart = cp.index;
  }

  const estPrimary = Math.ceil(((primaryJobs.length - primaryStart) * DELAY_MS) / 60_000);
  console.log(`\nPhase 1: ${primaryJobs.length} FT checks (~${estPrimary} min / ~${(estPrimary / 60).toFixed(1)} hrs)`);

  if (resumeMode && results.length) {
    console.log(`${results.length} previous results loaded`);
    if (cp) console.log(`Resuming from ${cp.phase} #${cp.index}\n`);
  }

  // Track which base+sticker combos have hits
  const hitsSet = new Set<string>();
  // Load from existing results
  for (const r of results) {
    hitsSet.add(`${baseName(r.skin)}|||${r.sticker}`);
  }

  // Phase 1: primary checks
  for (let i = primaryStart; i < primaryJobs.length; i++) {
    const { base, ftSkin, sticker } = primaryJobs[i];
    checked++;
    const pct = ((i / primaryJobs.length) * 100).toFixed(1);
    const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);
    process.stdout.write(`[P1 ${pct}% ${elapsed}m] ${ftSkin} | ${sticker}... `);

    const result = await checkSkin(ftSkin, sticker);
    if (result) {
      console.log(`FOUND ${result.totalListings} @ $${result.cheapest?.toFixed(2) ?? "?"}`);
      results.push(result);
      hitsSet.add(`${base}|||${sticker}`);
    } else {
      console.log("-");
    }

    if (checked % 10 === 0) {
      await saveCheckpoint({ phase: "primary", index: i + 1 });
      await saveResults(results);
      if (checked % 50 === 0) await gitPush(`P1: ${results.length} found (${((i / primaryJobs.length) * 100).toFixed(0)}%)`);
    }

    const delay = consecutiveFailures > 2 ? DELAY_MS * 2 : DELAY_MS;
    await sleep(delay);
  }

  await saveResults(results);
  await gitPush(`P1 complete: ${results.length} results`);

  // Phase 2: expand hits — check other wears/stattrak/souvenir for skins that had hits
  const expandJobs: { skin: string; sticker: string }[] = [];
  for (const key of hitsSet) {
    const [base, sticker] = key.split("|||");
    const variants = getVariants(allSkins, base);
    for (const v of variants) {
      // Skip the FT variant we already checked
      if (v.includes(`(${PRIMARY_WEAR})`) && !v.startsWith("StatTrak") && !v.startsWith("Souvenir")) continue;
      // Skip if already in results
      if (results.some((r) => r.skin === v && r.sticker === sticker)) continue;
      expandJobs.push({ skin: v, sticker });
    }
  }

  if (expandJobs.length > 0) {
    const estExpand = Math.ceil(((expandJobs.length - expandStart) * DELAY_MS) / 60_000);
    console.log(`\nPhase 2: ${expandJobs.length} variant checks for ${hitsSet.size} hits (~${estExpand} min)`);

    for (let i = expandStart; i < expandJobs.length; i++) {
      const { skin, sticker } = expandJobs[i];
      checked++;
      const pct = ((i / expandJobs.length) * 100).toFixed(1);
      const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);
      process.stdout.write(`[P2 ${pct}% ${elapsed}m] ${skin} | ${sticker}... `);

      const result = await checkSkin(skin, sticker);
      if (result) {
        console.log(`FOUND ${result.totalListings} @ $${result.cheapest?.toFixed(2) ?? "?"}`);
        results.push(result);
      } else {
        console.log("-");
      }

      if (checked % 10 === 0) {
        await saveCheckpoint({ phase: "expand", index: i + 1 });
        await saveResults(results);
        if (checked % 50 === 0) await gitPush(`P2: ${results.length} found`);
      }

      const delay = consecutiveFailures > 2 ? DELAY_MS * 2 : DELAY_MS;
      await sleep(delay);
    }
  } else {
    console.log("\nPhase 2: no hits to expand");
  }
}

// Final save
await saveResults(results);
try { require("fs").unlinkSync(CHECKPOINT_FILE); } catch {}
await gitPush(`DONE: ${results.length} results`);

// ---------------------------------------------------------------------------
// Summary — sorted by cheapest, with clickable links
// ---------------------------------------------------------------------------
console.log(`\n${"=".repeat(100)}`);
console.log(`DONE — ${results.length} skin+sticker combos with active listings`);
console.log(`Checked ${checked} queries in ${((Date.now() - startTime) / 60_000).toFixed(1)} min`);
console.log(`Results saved to ${RESULTS_FILE}`);
console.log(`${"=".repeat(100)}\n`);

for (const sticker of stickersToSearch) {
  const group = results
    .filter((r) => r.sticker === sticker)
    .sort((a, b) => (a.cheapest ?? Infinity) - (b.cheapest ?? Infinity));

  if (!group.length) {
    console.log(`\n--- ${sticker}: no listings found ---\n`);
    continue;
  }

  console.log(`\n--- ${sticker} (${group.length} skins with listings) ---\n`);

  for (const r of group) {
    const price = r.cheapest ? `$${r.cheapest.toFixed(2)}` : "price unknown";
    console.log(`  ${r.skin}`);
    console.log(`    ${r.totalListings} listing(s), cheapest: ${price}`);
    console.log(`    ${r.marketUrl}`);
    console.log();
  }
}
